### ISSUE TITLE
Broken links to reference

### ISSUE THREAD

**Issue by sjparsons** [braintree/custom-actions-docs#8]
I found some broken links, but I don't know how to fix them since I'm not sure where they should point. I added a branch in my fork that changes the target to `BAD_LINK` just to identify them.  Seeking input on where to point them to.

https://github.com/braintree/custom-actions-docs/compare/master...sjparsons:fix-broken-link

**Comment by kyledetella** [comment]
Thanks. Those don't really have to link anywhere right now. We could just make them normal text.

**Comment by sjparsons** [comment]
I removed the broken links in gitbook, so closing the issue now.
